github:
  is_project_page: false 
  is_user_page: false
  public: false 
  repository_url: http://linkedin.com/in/mjliu 
  
show_downloads: false

author:
  name: M.J.
  url: http://mjliu.com
  
theme: jekyll-theme-tactile 
title: M.
description: Simplicity is the ultimate sophistication.

google_analytics: UA-50968899-1

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
#  email: "someone@example.com"
  facebook: mjliu
#  github: mikexl
#  twitter: tigerplusdragon
#  rss: true
#  reddit: yourname
  linkedin: mjliu
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "http://facebook.com/mjliu"
